const ShopTypes = {
  UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILRE: 'FETCH_COLLECTIONS_FAILRE'
}

export default ShopTypes;
